# This file will be configured to contain variables for CPack. These variables
# should be set in the CMake list file of the project before CPack module is
# included. The list of available CPACK_xxx variables and their associated
# documentation may be obtained using
#  cpack --help-variable-list
#
# Some variables are common to all generators (e.g. CPACK_PACKAGE_NAME)
# and some are specific to a generator
# (e.g. CPACK_NSIS_EXTRA_INSTALL_COMMANDS). The generator specific variables
# usually begin with CPACK_<GENNAME>_xxxx.


SET(CPACK_BINARY_7Z "")
SET(CPACK_BINARY_BUNDLE "")
SET(CPACK_BINARY_CYGWIN "")
SET(CPACK_BINARY_DEB "")
SET(CPACK_BINARY_DRAGNDROP "")
SET(CPACK_BINARY_IFW "")
SET(CPACK_BINARY_NSIS "")
SET(CPACK_BINARY_OSXX11 "")
SET(CPACK_BINARY_PACKAGEMAKER "")
SET(CPACK_BINARY_RPM "")
SET(CPACK_BINARY_STGZ "")
SET(CPACK_BINARY_TBZ2 "")
SET(CPACK_BINARY_TGZ "")
SET(CPACK_BINARY_TXZ "")
SET(CPACK_BINARY_TZ "")
SET(CPACK_BINARY_WIX "")
SET(CPACK_BINARY_ZIP "")
SET(CPACK_CMAKE_GENERATOR "Visual Studio 12 2013")
SET(CPACK_COMPONENTS_ALL " pcl_common pcl_kdtree pcl_octree pcl_search pcl_sample_consensus pcl_filters pcl_2d pcl_geometry pcl_io pcl_features pcl_ml pcl_segmentation pcl_visualization pcl_surface pcl_registration pcl_keypoints pcl_tracking pcl_recognition pcl_stereo pcl_apps pcl_outofcore pcl_people pcl_tools pclconfig")
SET(CPACK_COMPONENTS_ALL_SET_BY_USER "TRUE")
SET(CPACK_COMPONENT_UNSPECIFIED_HIDDEN "TRUE")
SET(CPACK_COMPONENT_UNSPECIFIED_REQUIRED "TRUE")
SET(CPACK_GENERATOR "NSIS")
SET(CPACK_INSTALL_CMAKE_PROJECTS "F:/pcl_source_1.7.2/build_pcl_master;PCL;ALL;/")
SET(CPACK_INSTALL_PREFIX "C:/Program Files (x86)/PCL")
SET(CPACK_MODULE_PATH "F:/pcl_source_1.7.2/pcl-master/pcl-master/cmake/Modules/;F:/Program Files (x86)/VTK/lib/cmake/vtk-6.3")
SET(CPACK_NSIS_DISPLAY_NAME "PCL 1.8.1-dev")
SET(CPACK_NSIS_INSTALLER_ICON_CODE "")
SET(CPACK_NSIS_INSTALLER_MUI_ICON_CODE "")
SET(CPACK_NSIS_INSTALL_ROOT "$PROGRAMFILES32")
SET(CPACK_NSIS_PACKAGE_NAME "PCL-1.8.1-dev-msvc2013-win32")
SET(CPACK_OUTPUT_CONFIG_FILE "F:/pcl_source_1.7.2/build_pcl_master/CPackConfig.cmake")
SET(CPACK_PACKAGE_CONFIG_INSTALL_DIR "cmake")
SET(CPACK_PACKAGE_DEFAULT_LOCATION "/")
SET(CPACK_PACKAGE_DESCRIPTION_FILE "F:/cmake/Cmake_3.3.2/share/cmake-3.3/Templates/CPack.GenericDescription.txt")
SET(CPACK_PACKAGE_DESCRIPTION_SUMMARY "PCL built using CMake")
SET(CPACK_PACKAGE_FILE_NAME "PCL-1.8.1-dev-msvc2013-win32")
SET(CPACK_PACKAGE_INSTALL_DIRECTORY "PCL 1.8.1-dev")
SET(CPACK_PACKAGE_INSTALL_REGISTRY_KEY "PCL 1.8.1-dev win32")
SET(CPACK_PACKAGE_NAME "PCL")
SET(CPACK_PACKAGE_RELOCATABLE "true")
SET(CPACK_PACKAGE_VENDOR "Humanity")
SET(CPACK_PACKAGE_VERSION "1.8.1-dev")
SET(CPACK_PACKAGE_VERSION_MAJOR "1")
SET(CPACK_PACKAGE_VERSION_MINOR "8")
SET(CPACK_PACKAGE_VERSION_PATCH "1")
SET(CPACK_PROJECT_CONFIG_FILE "F:/pcl_source_1.7.2/build_pcl_master/cpack_options.cmake")
SET(CPACK_RESOURCE_FILE_LICENSE "F:/cmake/Cmake_3.3.2/share/cmake-3.3/Templates/CPack.GenericLicense.txt")
SET(CPACK_RESOURCE_FILE_README "F:/cmake/Cmake_3.3.2/share/cmake-3.3/Templates/CPack.GenericDescription.txt")
SET(CPACK_RESOURCE_FILE_WELCOME "F:/cmake/Cmake_3.3.2/share/cmake-3.3/Templates/CPack.GenericWelcome.txt")
SET(CPACK_SET_DESTDIR "OFF")
SET(CPACK_SOURCE_7Z "ON")
SET(CPACK_SOURCE_CYGWIN "")
SET(CPACK_SOURCE_GENERATOR "7Z;ZIP")
SET(CPACK_SOURCE_OUTPUT_CONFIG_FILE "F:/pcl_source_1.7.2/build_pcl_master/CPackSourceConfig.cmake")
SET(CPACK_SOURCE_TBZ2 "")
SET(CPACK_SOURCE_TGZ "")
SET(CPACK_SOURCE_TXZ "")
SET(CPACK_SOURCE_TZ "")
SET(CPACK_SOURCE_ZIP "ON")
SET(CPACK_SYSTEM_NAME "win32")
SET(CPACK_TOPLEVEL_TAG "win32")
SET(CPACK_WIX_SIZEOF_VOID_P "4")

if(NOT CPACK_PROPERTIES_FILE)
  set(CPACK_PROPERTIES_FILE "F:/pcl_source_1.7.2/build_pcl_master/CPackProperties.cmake")
endif()

if(EXISTS ${CPACK_PROPERTIES_FILE})
  include(${CPACK_PROPERTIES_FILE})
endif()
